### PR TITLE
Unzip

### PR DESCRIPTION
**Pull request by fneum**
> BTW, for git and pull requests it might be much better to have the source files directly in the repo rather than the source files in a zip archive.

I can only agree with @mbussieck, so here's a first pull request to get this started.

### CODE REVIEW

**Comment by Antti-L** [comment]
As the maintainer of TIMES, I disagree about having the source code files directly in the repo.  The source code is not maintained under Github, it is only distributed via Github.

**Comment by willu47** [comment]
@Antti-L - typically you would use Github releases to distribute or deploy a piece of software. A normal release schedule would have you tag a particular version of the source code which then creates the release.

**Comment by Antti-L** [comment]
> Without being able to view the source files directly in the repository, then no one else can meaningfully contribute to the development of the source code.

@willu47 Well, thus far ETSAP users have been well able to contribute to the code develoment, by reporting any problems in the code and submitting proposals for new features. That was so before using Github for distributing TIMES.  Recently, it was a decision made by the ETSAP Executive Committee to consider distributing TIMES via Github, and so the code is now available here. But it was also decided by ETSAP that only the ETSAP maintainer can commit changes to the source code.  If you now say that no one can any longer meaningfully contribute (because the code is now available here), I don't see how that could possibly be the case. I think they can still contribute, and even better than before, because now they can use also this channel for communicating any issues or proposals.

The zip in the Master repo is the latest release of the code. You are right that the "Github release" v4.4.0 is a zip of that release, and so it is basically just an archive of the release v4.4.0.  When new versions are released, users would thus still be able to easily download older releases as well.

**Comment by Antti-L** [comment]
In my view **Issues** is one of the core tools of Github, and it can be great for 1) filing bug reports, and 2) submitting feature and enhancement requests, and discussing all the necessary details about them. In Issues, you can insert code snippets, links and attachments that demonstrate the issue or describe the proposed enhancement in detail. Then, when a consensus is reached about the issue, the maintainer can proceed by implementing the fix or the new feature, and integrate it in the next release of the ETSAP TIMES code. I think that is also a reasonably efficient way of managing these kind of contributions, without any need for "pull requests". For eventual bigger projects a different workflow may be useful in separate branches, but not in the Master. What is in the Master is meant to be **stable and deployable production code**, and so it seems just right to me that one doesn't mess with the current TIMES release in the Master.

**Comment by fneum** [comment]
@mbussieck, @willu47 and I are trying to give you most well-intentioned and constructive feedback that can make your life and the life of others who want to work with your model much easier.

I have noted down a couple of comments below with which I hope to dissipate your reservations.

## Binaries in `git` repositories

There are a couple of issues with binaries in `git` repositories, but I will just name two:

- The neat thing about `git` is that it is very easy to see what changes were made with each commit. You can use this for instance to track down when a bug was introduced. All this is however only possible for text files! `git` cannot produce a diff of binary files, such as a `.zip` file.
- Moreover, as `git` cannot produce such a diff for binaries it will store a copy of each version of each binary file ever commited. This may increase the repository size rapidly over time. 

For more reading, follow: https://medium.com/@buzaa/why-you-should-not-push-binary-files-to-git-and-what-to-do-if-you-do-29f34692cef0

## Issues and Pull Requests

We are on the same page that issues are great for

> 1) filing bug reports, and 2) submitting feature and enhancement requests, and discussing all the necessary details about them.

Very often it comes in handy to refer to specific lines in the code. For instance I can direct you to lines 114 to 116 of `COPYING.txt` via

https://github.com/etsap-TIMES/TIMES_model/blob/master/COPYING.txt#L114-L116

Is this possible for the `.zip` file or its contents? No. 

You write that

> when a consensus is reached about the issue, the maintainer can proceed by implementing the fix or the new feature, and integrate it in the next release of the ETSAP TIMES code.

But how great would it be if others could draft features and bug fixes for you and share them easily with you? This is where the pull request comes in.

As you see at the example of this pull request there is plenty of opportunity left for discussion and the process of reaching a consensus. The difference -- and advantage of pull requests over issues -- is that code snippets can directly fuse into the main code base. Github provides extensive collaborative code review functionalities and tools.

It is highly unlikely to profit from any community engagement when not using pull requests for new features/bugfixes.

> But it was also decided by ETSAP that only the ETSAP maintainer can commit changes to the source code.

This pull request is in fact a very good example how you as maintainer keep in full control of additions to the model. In the end it is fully up to you (or your co-maintainers) to close or merge my proposal.

## Master branch

> For eventual bigger projects a different workflow may be useful in separate branches.

This usually makes sense even for smaller features and bug fixes. These branches are then merged into the `master`. The `master` branch collects code additions until the next release is to be made. Then do `git tag v0.x.x` and it'll appear at https://github.com/etsap-TIMES/TIMES_model/releases. This is actually the 

> stable and deployable production code

you were referring to, not the `master` branch! The `master` branch is for continuous development. You can check a release tag out any time with `git checkout tags/v0.x.x -b master` or simply download the (then) `.zip`.

By following this workflow

> one doesn't mess with the current TIMES release in the Master

but instead paves the way towards the next release, possibly in collaboration with others.

If you feel eager to learn more about the recommended workflows on github, start for example here: https://guides.github.com/introduction/flow/

Even if you are not fond of the idea of others contributing code, it does make sense to unzip. This way the community can easily see what code was changed between the versions.

I hope I could convince you!

**Comment by etsap-TIMES** [comment]
Contribution to TIMES is currently done through "Issues" in GitHub which can be used for filing bug reports, and submitting feature and enhancement requests, and discussing all the necessary details about them. In Issues, you can insert code snippets, links and attachments that demonstrate the issue or describe the proposed enhancement in detail. When a consensus is reached about an issue, the maintainer of TIMES will proceed by implementing the fix or the new feature, and integrate it in the next release of the ETSAP TIMES code. Currently the TIMES code is maintained by @Antti-L.

**Pull request closed without merging**
